// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqGjaHktccd9fG_kuPWICsW98WtMDV4o4',
    appId: '1:486152463177:web:89d5fda4d812744b26f098',
    messagingSenderId: '486152463177',
    projectId: 'savy-d40cc',
    authDomain: 'savy-d40cc.firebaseapp.com',
    storageBucket: 'savy-d40cc.firebasestorage.app',
    measurementId: 'G-QJ2LT8RBVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrX8irFrJaotfxTSXjy4JNx71BSTAp_pY',
    appId: '1:486152463177:android:7331a42750853acb26f098',
    messagingSenderId: '486152463177',
    projectId: 'savy-d40cc',
    storageBucket: 'savy-d40cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbdicwBx20crjDzZmgZbM3jLqwSwKGmec',
    appId: '1:486152463177:ios:d2f7767513594a4826f098',
    messagingSenderId: '486152463177',
    projectId: 'savy-d40cc',
    storageBucket: 'savy-d40cc.firebasestorage.app',
    iosBundleId: 'com.example.savy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbdicwBx20crjDzZmgZbM3jLqwSwKGmec',
    appId: '1:486152463177:ios:d2f7767513594a4826f098',
    messagingSenderId: '486152463177',
    projectId: 'savy-d40cc',
    storageBucket: 'savy-d40cc.firebasestorage.app',
    iosBundleId: 'com.example.savy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqGjaHktccd9fG_kuPWICsW98WtMDV4o4',
    appId: '1:486152463177:web:54adb3bf7b5cea9c26f098',
    messagingSenderId: '486152463177',
    projectId: 'savy-d40cc',
    authDomain: 'savy-d40cc.firebaseapp.com',
    storageBucket: 'savy-d40cc.firebasestorage.app',
    measurementId: 'G-SZN42MH2VY',
  );
}
